project:
  title: "rzine-quarto-extension"
  render: 
    - rzine-quarto-extension.qmd
  resources: 
    - environment.yml
    - .nojekyll

execute: 
  cache: true
  freeze: auto

format:
  rzine-html: 
    output-file: index.html
  rzine-pdf: default  